services:
  marz_balancer:
    build: .
    container_name: marz_balancer
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8023}:8023"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./marz_balancer.py:/app/marz_balancer.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./.env:/app/.env:ro
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python marz_balancer.py"